function Hd = fpa_bp_2_10
%FPA_BP_2_10 Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.12 and the Signal Processing Toolbox 6.15.
%
% Generated on: 27-Aug-2012 21:36:00
%

% Elliptic Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 33;  % Sampling Frequency

N      = 4;   % Order
Fpass1 = 2;   % First Passband Frequency
Fpass2 = 10;  % Second Passband Frequency
Apass  = 1;   % Passband Ripple (dB)
Astop  = 80;  % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.bandpass('N,Fp1,Fp2,Ast1,Ap,Ast2', N, Fpass1, Fpass2, ...
                      Astop, Apass, Astop, Fs);
Hd = design(h, 'ellip');

% [EOF]
